# .streamlit/secrets.toml
GEMINI_API_KEY = "AIzaSyC9p8IL8DiCXsNQ4LVyLLuRlBPM90OqoYE"
FINNHUB_API_KEY = "d6823opr01qobepjohsgd6823opr01qobepjoht0"
GAS_WEBAPP_URL = "https://script.google.com/macros/s/AKfycbzpPMkeIAgkg4tp1RPPLE2B3r22oVlJs5wV_vRlkI_PQjaWsg_lF93yHfZvNvYogaViFQ/exec"
SUPABASE_URL = "https://pbdwzpktugztklejzvhn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZHd6cGt0dWd6dGtsZWp6dmhuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTAzODczNywiZXhwIjoyMDg2NjE0NzM3fQ.KpSs6BF-6TkAhI6INJzm9LW0GEFiI2_hQVg_cZ7i9cc"
JQUANTS_API_KEY = "uY6GLWJM-t5MIiekSB3viK7EPe4J-SSCFX_1n1PnVKI"
EDINET_API_KEY = "edb_8bb85e00b34d7c54e558882fd3d835f5"
